# Site settings
title: V的个人静态博客
description: 记录学习过程和个人能力展示
author: V
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://i1to.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Theme settings
theme: minima

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "V"
      
# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
